# Generated by Django 5.0.3 on 2024-03-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('complete', models.BooleanField()),
                ('ToDo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.todo')),
            ],
        ),
    ]
