# Generated by Django 5.0.3 on 2024-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(default='Default'),
        ),
        migrations.AddField(
            model_name='workout',
            name='repetitions',
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.PositiveBigIntegerField(default=4),
        ),
    ]
