# Generated by Django 5.0.3 on 2024-03-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_workout_description_workout_repetitions_workout_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='ToDo',
        ),
    ]
